name: Tests

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install azure-cli
      - name: Login via Azure CLI
        run: |
          az login --tenant ${{ secrets.AZURE_TENANT_ID }} -u ${{ secrets.AZURE_USERNAME }} -p ${{ secrets.AZURE_PASSWORD }}

      - name: Helm install
        run: pip install helm

        # se mettre dans le dossier tp3_devops pour lancer le terraform

      - name: Terraform init and validate
        uses: hashicorp/setup-terraform@v2
      - run: cd terraformpart && terraform init && terraform fmt && terraform validate && terraform plan
      # - run: terraform fmt
      # - run: terraform validate
      # - run: terraform plan

      - name: humanvalidation
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.TOKEN }}
          approvers: Setsuko34
          minimum-approvals: 1
          issue-title: "Approuver pour lancer le terraform apply"
          issue-body: "Dites 'yes' pour approuver le lancement du terraform apply"
          exclude-workflow-initiator-as-approver: false
      - name: terraform apply
        run: cd terraformpart && terraform apply -auto-approve

      # - name: Helm init
      #   run: helm init
      - name: quit the folder
        run: cd ..
      - name: Helm install
        run: helm install --kubeconfig tp3_devops/.kube/config vote-app kubepart/deploy-votingapp/
        #run: helm install tp3-devops ./tp3_devops/helm
